name: learn-github-actions
on:
  push:
    branches:
      - master
      - 'develop'
      - 'releases/**'
      - '!releases/**-alpha'
    tags:
      - '*'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - run: cat output.log